language: scala

jdk:
  - openjdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.coursier

script:
  - sbt '++ 0.24.0-RC1!' coreJVM/compile
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs --no-run-if-empty rm
